apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: metadata-grpc-service
spec:
  host: metadata-grpc-service.kubeflow.svc.{{< .Values.clusterDomain >}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
